# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='TranslatedHostsIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('translated_description', models.TextField()),
                ('author', models.CharField(default='Sistema', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'hostnames',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='host',
            field=models.ManyToManyField(to='core.TranslatedHostsIssues'),
        ),
    ]
