# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedhostsissues',
            name='translated_description',
            field=models.TextField(null=True),
        ),
    ]
