# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170630_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='evandro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
