# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_groups_evandro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'grupos',
                'verbose_name': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('author', models.CharField(default='Sistema', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'mensagens',
                'verbose_name': 'mensagem',
            },
        ),
        migrations.RemoveField(
            model_name='groups',
            name='host',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='TranslatedHostsIssues',
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(to='core.Messages'),
        ),
    ]
