# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170710_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='core.Messages'),
        ),
    ]
