# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170711_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='Mensagem'),
            preserve_default=False,
        ),
    ]
