# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_message_detailed_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='detailed_message',
            field=models.TextField(max_length=1000, verbose_name='Mensagem técnica detalhada'),
        ),
    ]
