# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_message_notification_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='notification_groups',
        ),
    ]
