# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_notifications', '0002_auto_20170809_1359'),
        ('profiles_manager', '0005_userprofile_notification_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_groups',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_groups',
            field=models.ManyToManyField(to='mail_notifications.NotificationGroup', verbose_name='Grupos de notificação de e-mail'),
        ),
    ]
