# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_manager', '0006_auto_20170809_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_groups',
            field=models.ManyToManyField(blank=True, to='mail_notifications.NotificationGroup', verbose_name='Grupos de notificação de e-mail'),
        ),
    ]
