# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_ldap_group_name', models.CharField(max_length=30, verbose_name='Email ou grupo do ldap')),
                ('groups', models.ManyToManyField(to='mail_notifications.NotificationGroup', verbose_name='Grupos de notificação')),
            ],
        ),
    ]
