# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='groups',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
