# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_message_notification_groups'),
        ('profiles_manager', '0008_auto_20170811_1042'),
        ('mail_notifications', '0002_auto_20170809_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationGroup',
        ),
    ]
